version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - postgres

  orderservice:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    depends_on:
      - postgres
      - userservice

volumes:
  postgres_data: