// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_order.proto

package ru.itis.user.proto;

public final class UserOrder {
  private UserOrder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateOrderRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020user_order.proto\"\036\n\013UserRequest\022\017\n\007use" +
      "r_id\030\001 \001(\003\"<\n\014UserResponse\022\017\n\007user_id\030\001 " +
      "\001(\003\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\"0\n\021Crea" +
      "teUserRequest\022\014\n\004name\030\001 \001(\t\022\r\n\005email\030\002 \001" +
      "(\t\" \n\014OrderRequest\022\020\n\010order_id\030\001 \001(\003\"H\n\r" +
      "OrderResponse\022\020\n\010order_id\030\001 \001(\003\022\024\n\014produ" +
      "ct_name\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\003\";\n\022Create" +
      "OrderRequest\022\024\n\014product_name\030\001 \001(\t\022\017\n\007us" +
      "er_id\030\002 \001(\0032f\n\013UserService\022&\n\007GetUser\022\014." +
      "UserRequest\032\r.UserResponse\022/\n\nCreateUser" +
      "\022\022.CreateUserRequest\032\r.UserResponse2m\n\014O" +
      "rderService\022)\n\010GetOrder\022\r.OrderRequest\032\016" +
      ".OrderResponse\0222\n\013CreateOrder\022\023.CreateOr" +
      "derRequest\032\016.OrderResponseB\026\n\022ru.itis.us" +
      "er.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserResponse_descriptor,
        new java.lang.String[] { "UserId", "Name", "Email", });
    internal_static_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateUserRequest_descriptor,
        new java.lang.String[] { "Name", "Email", });
    internal_static_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRequest_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderResponse_descriptor,
        new java.lang.String[] { "OrderId", "ProductName", "UserId", });
    internal_static_CreateOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CreateOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateOrderRequest_descriptor,
        new java.lang.String[] { "ProductName", "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
