// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_order.proto

package ru.itis.user.proto;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
